"""Add vote_date scrutin category

Revision ID: 1f726fc15d84
Revises: 234647c8e9eb
Create Date: 2026-03-19 14:17:03.851832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f726fc15d84'
down_revision: Union[str, Sequence[str], None] = '234647c8e9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('law', sa.Column('vote_date', sa.DateTime(), nullable=True))
    op.add_column('law', sa.Column('scrutin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('law', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_law_scrutin_id'), 'law', ['scrutin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_law_scrutin_id'), table_name='law')
    op.drop_column('law', 'category')
    op.drop_column('law', 'scrutin_id')
    op.drop_column('law', 'vote_date')
    # ### end Alembic commands ###
