"""Add all tables for facultative user_data

Revision ID: 3c856eb39c05
Revises: 567e91a6cf48
Create Date: 2026-03-05 10:36:45.428263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c856eb39c05'
down_revision: Union[str, Sequence[str], None] = '567e91a6cf48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genderidentities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genderidentities_name'), 'genderidentities', ['name'], unique=False)
    op.create_table('professionalstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionalstatus_name'), 'professionalstatus', ['name'], unique=False)
    op.create_table('socialstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socialstatus_name'), 'socialstatus', ['name'], unique=False)
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_status_id', sa.Integer(), nullable=True),
    sa.Column('social_status_id', sa.Integer(), nullable=True),
    sa.Column('gender_identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_identity_id'], ['genderidentities.id'], ),
    sa.ForeignKeyConstraint(['professional_status_id'], ['professionalstatus.id'], ),
    sa.ForeignKeyConstraint(['social_status_id'], ['socialstatus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    op.drop_index(op.f('ix_socialstatus_name'), table_name='socialstatus')
    op.drop_table('socialstatus')
    op.drop_index(op.f('ix_professionalstatus_name'), table_name='professionalstatus')
    op.drop_table('professionalstatus')
    op.drop_index(op.f('ix_genderidentities_name'), table_name='genderidentities')
    op.drop_table('genderidentities')
    # ### end Alembic commands ###
