"""fix_partyvote_user_id_to_party_id

Revision ID: 5360b77ec63d
Revises: cf648fe60467
Create Date: 2026-06-30 09:53:27.048350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5360b77ec63d'
down_revision: Union[str, Sequence[str], None] = 'cf648fe60467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partyvote', sa.Column('party_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_partyvote_user_id'), table_name='partyvote')
    op.create_index(op.f('ix_partyvote_party_id'), 'partyvote', ['party_id'], unique=False)
    op.drop_constraint(op.f('partyvote_user_id_fkey'), 'partyvote', type_='foreignkey')
    op.create_foreign_key(None, 'partyvote', 'politicalparty', ['party_id'], ['id'])
    op.drop_column('partyvote', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partyvote', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'partyvote', type_='foreignkey')
    op.create_foreign_key(op.f('partyvote_user_id_fkey'), 'partyvote', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_partyvote_party_id'), table_name='partyvote')
    op.create_index(op.f('ix_partyvote_user_id'), 'partyvote', ['user_id'], unique=False)
    op.drop_column('partyvote', 'party_id')
    # ### end Alembic commands ###
