"""Add country and institution tables with power and institution_type references

Revision ID: 55c1c776a374
Revises: 3c856eb39c05
Create Date: 2026-03-11 12:19:17.349227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c1c776a374'
down_revision: Union[str, Sequence[str], None] = '3c856eb39c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iso_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_iso_code'), 'country', ['iso_code'], unique=True)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.create_table('institutiontype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutiontype_name'), 'institutiontype', ['name'], unique=True)
    op.create_table('power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_name'), 'power', ['name'], unique=True)
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.Column('institution_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institution_type_id'], ['institutiontype.id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['power.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_country_id'), 'institution', ['country_id'], unique=False)
    op.create_index(op.f('ix_institution_institution_type_id'), 'institution', ['institution_type_id'], unique=False)
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=False)
    op.create_index(op.f('ix_institution_power_id'), 'institution', ['power_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_power_id'), table_name='institution')
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.drop_index(op.f('ix_institution_institution_type_id'), table_name='institution')
    op.drop_index(op.f('ix_institution_country_id'), table_name='institution')
    op.drop_table('institution')
    op.drop_index(op.f('ix_power_name'), table_name='power')
    op.drop_table('power')
    op.drop_index(op.f('ix_institutiontype_name'), table_name='institutiontype')
    op.drop_table('institutiontype')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_iso_code'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
