"""add political figures and political party modules

Revision ID: b22edfd6f5ba
Revises: 55c1c776a374
Create Date: 2026-03-11 13:58:30.886651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22edfd6f5ba'
down_revision: Union[str, Sequence[str], None] = '55c1c776a374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_name'), 'domain', ['name'], unique=False)
    op.create_table('electiontype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politicalparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ideology_summary', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicalparty_abbreviation'), 'politicalparty', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_politicalparty_country_id'), 'politicalparty', ['country_id'], unique=False)
    op.create_index(op.f('ix_politicalparty_name'), 'politicalparty', ['name'], unique=False)
    op.create_table('politicalfigure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['politicalparty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicalfigure_country_id'), 'politicalfigure', ['country_id'], unique=False)
    op.create_index(op.f('ix_politicalfigure_last_name'), 'politicalfigure', ['last_name'], unique=False)
    op.create_index(op.f('ix_politicalfigure_name'), 'politicalfigure', ['name'], unique=False)
    op.create_index(op.f('ix_politicalfigure_party_id'), 'politicalfigure', ['party_id'], unique=False)
    op.create_table('politicalprogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('election_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_type_id'], ['electiontype.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['politicalparty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicalprogram_election_type_id'), 'politicalprogram', ['election_type_id'], unique=False)
    op.create_index(op.f('ix_politicalprogram_name'), 'politicalprogram', ['name'], unique=False)
    op.create_index(op.f('ix_politicalprogram_party_id'), 'politicalprogram', ['party_id'], unique=False)
    op.create_index(op.f('ix_politicalprogram_year'), 'politicalprogram', ['year'], unique=False)
    op.create_table('politicalrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('figure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['politicalfigure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicalrole_figure_id'), 'politicalrole', ['figure_id'], unique=False)
    op.create_index(op.f('ix_politicalrole_name'), 'politicalrole', ['name'], unique=False)
    op.create_table('politicaltopic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['politicalprogram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicaltopic_domain_id'), 'politicaltopic', ['domain_id'], unique=False)
    op.create_index(op.f('ix_politicaltopic_program_id'), 'politicaltopic', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_politicaltopic_program_id'), table_name='politicaltopic')
    op.drop_index(op.f('ix_politicaltopic_domain_id'), table_name='politicaltopic')
    op.drop_table('politicaltopic')
    op.drop_index(op.f('ix_politicalrole_name'), table_name='politicalrole')
    op.drop_index(op.f('ix_politicalrole_figure_id'), table_name='politicalrole')
    op.drop_table('politicalrole')
    op.drop_index(op.f('ix_politicalprogram_year'), table_name='politicalprogram')
    op.drop_index(op.f('ix_politicalprogram_party_id'), table_name='politicalprogram')
    op.drop_index(op.f('ix_politicalprogram_name'), table_name='politicalprogram')
    op.drop_index(op.f('ix_politicalprogram_election_type_id'), table_name='politicalprogram')
    op.drop_table('politicalprogram')
    op.drop_index(op.f('ix_politicalfigure_party_id'), table_name='politicalfigure')
    op.drop_index(op.f('ix_politicalfigure_name'), table_name='politicalfigure')
    op.drop_index(op.f('ix_politicalfigure_last_name'), table_name='politicalfigure')
    op.drop_index(op.f('ix_politicalfigure_country_id'), table_name='politicalfigure')
    op.drop_table('politicalfigure')
    op.drop_index(op.f('ix_politicalparty_name'), table_name='politicalparty')
    op.drop_index(op.f('ix_politicalparty_country_id'), table_name='politicalparty')
    op.drop_index(op.f('ix_politicalparty_abbreviation'), table_name='politicalparty')
    op.drop_table('politicalparty')
    op.drop_table('electiontype')
    op.drop_index(op.f('ix_domain_name'), table_name='domain')
    op.drop_table('domain')
    # ### end Alembic commands ###
