"""Add law and voting system tables including vote results and user votes and party vote

Revision ID: cf648fe60467
Revises: b22edfd6f5ba
Create Date: 2026-03-12 12:22:15.689118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf648fe60467'
down_revision: Union[str, Sequence[str], None] = 'b22edfd6f5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_position'), 'vote', ['position'], unique=True)
    op.create_table('law',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_country_id'), 'law', ['country_id'], unique=False)
    op.create_index(op.f('ix_law_domain_id'), 'law', ['domain_id'], unique=False)
    op.create_index(op.f('ix_law_source_url'), 'law', ['source_url'], unique=False)
    op.create_index(op.f('ix_law_title'), 'law', ['title'], unique=False)
    op.create_table('partyvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['law.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['vote.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partyvote_law_id'), 'partyvote', ['law_id'], unique=False)
    op.create_index(op.f('ix_partyvote_position_id'), 'partyvote', ['position_id'], unique=False)
    op.create_index(op.f('ix_partyvote_user_id'), 'partyvote', ['user_id'], unique=False)
    op.create_table('uservote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['law.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['vote.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uservote_law_id'), 'uservote', ['law_id'], unique=False)
    op.create_index(op.f('ix_uservote_position_id'), 'uservote', ['position_id'], unique=False)
    op.create_index(op.f('ix_uservote_user_id'), 'uservote', ['user_id'], unique=False)
    op.create_table('voteresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('total_for', sa.Integer(), nullable=False),
    sa.Column('total_abstention', sa.Integer(), nullable=False),
    sa.Column('total_against', sa.Integer(), nullable=False),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('vote_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['law_id'], ['law.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voteresult_institution_id'), 'voteresult', ['institution_id'], unique=False)
    op.create_index(op.f('ix_voteresult_law_id'), 'voteresult', ['law_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voteresult_law_id'), table_name='voteresult')
    op.drop_index(op.f('ix_voteresult_institution_id'), table_name='voteresult')
    op.drop_table('voteresult')
    op.drop_index(op.f('ix_uservote_user_id'), table_name='uservote')
    op.drop_index(op.f('ix_uservote_position_id'), table_name='uservote')
    op.drop_index(op.f('ix_uservote_law_id'), table_name='uservote')
    op.drop_table('uservote')
    op.drop_index(op.f('ix_partyvote_user_id'), table_name='partyvote')
    op.drop_index(op.f('ix_partyvote_position_id'), table_name='partyvote')
    op.drop_index(op.f('ix_partyvote_law_id'), table_name='partyvote')
    op.drop_table('partyvote')
    op.drop_index(op.f('ix_law_title'), table_name='law')
    op.drop_index(op.f('ix_law_source_url'), table_name='law')
    op.drop_index(op.f('ix_law_domain_id'), table_name='law')
    op.drop_index(op.f('ix_law_country_id'), table_name='law')
    op.drop_table('law')
    op.drop_index(op.f('ix_vote_position'), table_name='vote')
    op.drop_table('vote')
    # ### end Alembic commands ###
