"""Add phone_number to UserData

Revision ID: e68dac8d0026
Revises: 3c856eb39c05
Create Date: 2026-03-05 15:28:11.890514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e68dac8d0026'
down_revision: Union[str, Sequence[str], None] = '3c856eb39c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'phone_number')
    # ### end Alembic commands ###
